### ISSUE TITLE
ガウルちゃんが不細工になってしまう

### ISSUE THREAD

**Issue by BigSlick11** [jundoll/discordbot-BSPlaylistManager#19]
ゲーム画面でプレイリストのサムネイルを見るとガウルちゃんが不細工です。
画像が縦に引き伸ばされてしまっています。

1. おすすめ譜面プレイリストをインストールします
2. ビートセイバーを起動してカスタムマップ選択画面を開きます
3. おすすめ譜面プレイリストを見る
4. See error　oh-no-

**Comment by jundoll** [comment]
PlaylistLoaderLiteの画像表示が正方形に詰める仕様だったが原因でした。
Playlist内の画像を正方形に切り出した画像で置き換えて対応完了です。
