### ISSUE TITLE
[Request] 複数のプレイリストを同時に管理できるようにしてほしい

### ISSUE THREAD

**Issue by BigSlick11** [jundoll/discordbot-BSPlaylistManager#28]
例えば、
/add [Target Playlist Name] [URL] 
のように入力して、複数のプレイリストを扱うのはどうだろうか？

**Comment by jundoll** [comment]
複数プレイリストの管理機能は現在開発中です。年末年始中には更新を予定してます。

**Comment by jundoll** [comment]
実装完了しました。
使い方はREADMEを参照してください。
